name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag lxdmanager/backend:latest
      - name: Push the tagged Docker image
        run: docker push lxdmanager/backend:latest